=== alizeepace/claimstore/claimstore/static/json/schemas/claims/claim.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Claim",
  "description": "Claim provided by a service",
  "type": "object",
  "properties": {
    "claimant": {
      "description": "Short name of the service used for subscription",
      "value": "string"
    },
    "subject": {
      "description": "Subject of the predicate (claim)",
      "type": "object",
      "properties": {
        "type": {
          "description": "Type of persistent identifier (e.g. INSPIRE_RECORD_ID)",
          "type": "string"
        },
        "value": {
          "description": "Actual value of the identifier",
          "type": "string"
        }
      },
      "required": ["type", "value"],
      "additionalProperties": false
    },
    "claim": {
      "description": "Type of claim",
      "type": "object",
      "properties": {
        "predicate": {
          "description": "Predicate of the claim",
          "type": "string",
          "enum": ["is_same_as", "is_different_than", "is_erratum_of", "is_superseded_by", "is_cited_by", "is_software_for", "is_dataset_for"]
        },
        "created": {
          "description": "Datetime in which the claim was created",
          "type": "string",
          "format": "date-time"
        },
        "certainty": {
          "description": "Certainty of the claim (0 to 1.0)",
          "type": "number",
          "minimum": 0,
          "maximum": 1
        },
        "arguments": {
          "description": "Arguments supporting the certainty",
          "type": "object",
          "properties": {
            "human": {
              "description": "The claim was done by a human or an algorithm",
              "type": "number",
              "enum": [0, 1]
            },
            "actor": {
              "description": "Who assessed the certainty",
              "type": "string"
            },
            "role": {
              "description": "Role of the actor",
              "type": "string"
            }
          }
        }
      },
      "required": ["predicate", "certainty"]
    },
    "object": {
      "description": "Object of the predicate (claim)",
      "type": "object",
      "properties": {
        "type": {
          "description": "Type of persistent identifier (e.g. INSPIRE_RECORD_ID)",
          "type": "string"
        },
        "value": {
          "description": "Actual value of the identifier",
          "type": "string"
        }
      },
      "required": ["type", "value"],
      "additionalProperties": false
    }
  },
  "required": ["claimant", "subject", "claim", "object"],
  "additionalProperties": false
}

=== alizeepace/claimstore/claimstore/static/json/examples/claim.inspire.2.json
{
  "claimant": "INSPIRE",
  "subject": {
    "type": "INSPIRE_RECORD_ID",
    "value": "cond-mat/9906097"
  },
  "claim": {
    "predicate": "is_same_as",
    "created": "2015-05-25T11:00:00Z",
    "certainty": 0.5,
    "arguments": {
      "human": 1,
      "actor": "John Doe",
      "role": "cataloger"
    }
  },
  "object": {
    "type": "CDS_RECORD_ID",
    "value": "C10.1103/PhysRevE.62.7422"
  }
}

=== alizeepace/claimstore/claimstore/modules/claims/static/json/examples/claim.cds.1.json
{
  "claimant": "CDS",
  "subject": {
    "type": "CDS_RECORD_ID",
    "value": "2001192"
  },
  "claim": {
    "predicate": "is_same_as",
    "created": "2015-03-25T11:00:00Z",
    "certainty": 1.0,
    "arguments": {
      "human": 0,
      "actor": "CDS_submission"
    }
  },
  "object": {
    "type": "CDS_REPORT_NUMBER",
    "value": "CMS-PAS-HIG-14-008"
  }
}

=== alizeepace/claimstore/claimstore/modules/claims/static/json/examples/claim.inspire.2.json
{
  "claimant": "INSPIRE",
  "subject": {
    "type": "INSPIRE_RECORD_ID",
    "value": "cond-mat/9906097"
  },
  "claim": {
    "predicate": "is_cited_by",
    "created": "2015-05-25T11:00:00Z",
    "certainty": 0.5,
    "arguments": {
      "human": 1,
      "actor": "John Doe",
      "role": "cataloguer"
    }
  },
  "object": {
    "type": "CDS_RECORD_ID",
    "value": "2003192"
  }
}
